public enum SyntaxKind
{
    IdentifierToken,
    NumberToken,
    BooleanToken,
    StringToken,
    CommentToken,

    PlusToken,
    MinusToken,
    StarToken,
    SlashToken,

    LeftParenthesisToken,
    RightParenthesisToken,
    LeftBraceToken,
    RightBraceToken,
    LeftBracketToken,
    RightBracketToken,

    DoubleEqualsToken,
    DoubleAmpersandToken,
    BangEqualsToken,
    EqualsToken,
    CommaToken,
    SemiColonToken,
    ColonToken,
    LessThanToken,
    GreaterThanToken,
    PeriodToken,
    ArrowToken,
    DoublePipeToken,

    IfKeyword,
    ElseIfKeyword,
    ElseKeyword,
    ForKeyword,
    WhileKeyword,
    LetKeyword,
    ReturnKeyword,
    BreakKeyword,
    FuncKeyword,
    ConstKeyword,
    VoidKeyword,
    VarKeyword,

    Whitespace,
    EndOfFileToken,
}